# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/metagentools',
                'doc_host': 'https://vtecftwy.github.io',
                'git_url': 'https://github.com/vtecftwy/metagentools',
                'lib_path': 'metagentools'},
  'syms': {'metagentools.core': {'metagentools.core.foo': ('core.html#foo', 'metagentools/core.py')}}}