# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs-dev/02_art.ipynb.

# %% auto 0
__all__ = []

# %% ../nbs-dev/02_art.ipynb 2
# Imports all dependencies
import numpy as np
import os

from pathlib import Path
