# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs-dev/00_core.ipynb.

# %% auto 0
__all__ = ['temp_fcnt']

# %% ../nbs-dev/00_core.ipynb 5
def temp_fcnt(
    p: str, # string to print
):
    print(p)
